### Numpy library:
Numpy library in python is a powerful tool for working with arrays and materices.
numpy stands for numerical python
It is core library for numeric and scientific computing
It consists of multi dimentional array object and a collection of routines for processing those arrays

In [1]:
import numpy as np

### Array:
Array in numpy can only hold data of the same type.This helps in doing calculations and operations smoothly.

In [2]:
import numpy as np
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
result=arr1+arr2
print(result)

[ 7  9 11 13 15]


### Multi Dimentional array

In [45]:
import numpy as np
n2=np.array(([12,34,56],[23,45,67]))
n2

array([[12, 34, 56],
       [23, 45, 67]])

### Initializing numpy array

In [52]:
#Initializing Numpy arrays with zeros
import numpy as np 
n1=np.zeros((1,2))
n1

array([[0., 0.]])

In [47]:
import numpy as np 
n1=np.zeros((5,5))
n1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [49]:
#Initializing Numpy arrays with same numbers 
import numpy as np 
n1=np.full((3,3),10)
n1

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [50]:
#Initializing Numpy arrays within a range:
import numpy as np 
n1=np.arange(10,20)
n1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [51]:
#Initializing Numpy array with a random numbers:
import numpy as np 
n1=np.random.randint(1,100,8)
n1

array([80, 91, 89,  8, 19, 38, 40, 78])

### 1-D Arrays:
1-D array is like a list of elements arranged in single row 

In [7]:
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


### 2-D Arrays:
2-D Arrays also known as two dimensional array,is an array of array. 

In [8]:
arr =np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


### 3-D Arrays: 
A 3D array in python is like a collection of 2D arrays stacked on top of each other,creating a three dimensional structure.

In [2]:
arr=np.array([[[1,2,3],[4,5,6],[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]
  [1 2 3]
  [4 5 6]]]


### Indexing:
array indexing is the same as accessing an array elements.indexes in numpy array start with 0.

In [3]:
arr=np.array([1,2,3,4])
print(arr[0])

1


### Negative Indexing:

In [15]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,-2])

9


### Slicing array:
Slicing in python use to taking elements from one given index to another given index.[start:end]

In [16]:
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [17]:
arr=np.array([1,2,3,4,5,6,7])
print(arr[4:])

[5 6 7]


In [18]:
arr=np.array([1,2,3,4,5,6,7])
print(arr[:4])

[1 2 3 4]


### Negative Slicing:
Use the minus operator to refer to index from the end.

In [19]:
arr=np.array([1,2,3,4,5,6,7])
print(arr[-3:-1])

[5 6]


### Step:
use the step value to determine the step of the slicing.

In [20]:
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5:2])

[2 4]


In [21]:
arr=np.array([1,2,3,4,5,6,7])
print(arr[::2])

[1 3 5 7]


### Data type:  

In [27]:
#integers:use to represent integer numbers.
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr.dtype)

int32


In [30]:
#string:used to represent data,the text is given under quotw marks.
arr=np.array(['apple','banana','cherry'])
print(arr.dtype)


<U6


In [31]:
#Float:used to represent real numbers.
arr=np.array([1.2,2.5,3.7])
print(arr.dtype)

float64


In [32]:
#boolean: used to represent True or False.
arr=np.array([True,False,True,False])
print(arr.dtype)

bool


In [33]:
#complex: used to represent complex numbers
arr=np.array([2+3j,4-1j])
print(arr.dtype)

complex128


In [34]:
#Object: used to store any kind of python object in an array.
arr=np.array([{'a':1},[1,2,3]])
print(arr.dtype)

object


C:\Users\HP\AppData\Local\Temp\ipykernel_12112\2442920232.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr=np.array([{'a':1},[1,2,3]])


In [38]:
#datetime: It helps for handling dates and times with high precision in arrays.
arr=np.array(['2024-06-11','2024-6-12'],dtype='datetime64')
print(dates)

ValueError: Error parsing datetime string "2024-6-12" at position 5

In [39]:
#Converting data type:
arr=np.array([1.2,2.5,3.7])
newarr=arr.astype(int)
print(newarr)
print(newarr.dtype)


[1 2 3]
int32


### Joining Numpy arrays:
Here its join an two ar more array in single array.

In [43]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


### Sorting array

In [2]:
import numpy as np
arr=np.array([3,4,2,1])
print(np.sort(arr))

[1 2 3 4]


In [3]:
# sorting in Assending order (By-default)
x=np.array([1,4,5,7,3,8,3,9])
y=np.sort(x)
print(y)

[1 3 3 4 5 7 8 9]


In [4]:
# To sorting in Desending order
x=np.array([1,4,5,7,3,8,3,9])
y=np.sort(x)[::-1]
print(y)

[9 8 7 5 4 3 3 1]


In [5]:
x=np.array([1,4,5,7,3,8,3,9])
y=np.argsort(x)
print(y)

[0 4 6 1 2 3 5 7]


### Shape of numpy arrays

In [54]:
import numpy as np 
n1=np.array([[1,2,3],[4,5,6]])
n1.shape

(2, 3)